/**
 * `incidentFromAlert.ts` — Story 3.6.
 *
 * Pure helper that decides whether a just-committed Alert should
 * auto-create an Incident row, and builds the Incident-write
 * payload when it should.
 *
 * Decision rule (AC1, AC2):
 *   - `severity === "warning"` → create (medium-severity work item).
 *   - `severity === "critical"` → create (high-severity work item).
 *   - `severity === "info"` → do NOT create (informational only,
 *     per PRD §5.3 + the user's locked decision).
 *   - Any other severity → do NOT create. `Alert.severity` is a
 *     free-form `String` (NOT a Prisma enum); the wire-side Zod
 *     parse guarantees `info|warning|critical`, but defence-in-
 *     depth at the helper bounds the set to the known-good values.
 *
 * The helper is pure (no Prisma imports). It is called from inside
 * the `$transaction` callback in `applyTransition.ts:101-167`, so
 * the Incident row commits atomically with the Alert row + state
 * upsert. The P2002 race-catch path returns BEFORE this helper
 * is called, so the second writer does not create a duplicate
 * incident (AC3).
 *
 * What this helper does NOT do:
 *   - Emit a socket event (`incident:opened` is out of scope; Epic
 *     4 owns incident lifecycle emits).
 *   - Touch the Incident state machine (Epic 4's `state` enum is
 *     future work; 3.6 writes one row with the existing 5 columns).
 *   - Deduplicate across multiple alerts on the same `(deviceId,
 *     metric)` key (Epic 4's reopen path owns this).
 */
import {
  type IncidentCreatingSeverity,
  type RuleMetric,
  shouldCreateIncident as shouldCreateIncidentShared,
} from "@surakkha/shared";

/**
 * Closed set of severities that auto-create an Incident. Re-exported
 * from `@surakkha/shared/incident.ts` so api and db share one source
 * of truth (test rig at `alert-debounce.spec.ts` imports from shared).
 */
export type { IncidentCreatingSeverity };

/**
 * Re-export the shared predicate. Aliased back to the local name so
 * the call site in `applyTransition.ts` keeps its existing
 * `shouldCreateIncident(severity)` import path.
 */
export const shouldCreateIncident = shouldCreateIncidentShared;

/**
 * Input shape the helper needs from the alert row + transition
 * context. Slim on purpose — the alert row carries `deviceId,
 * metric` and the `transition` carries `severity, openedAt`; the
 * `value` is the triggering reading's metric value (carried in the
 * hook context, not on the Alert row itself).
 */
export interface IncidentFromAlertInput {
  readonly deviceId: string;
  readonly severity: string;
  readonly metric: RuleMetric;
  readonly value: number;
  readonly openedAt: Date;
}

/**
 * Build the `Incident` row payload from the alert's metadata.
 * Pure: no DB write — the caller passes the result to
 * `tx.incident.create({ data: ... })` inside the `$transaction`
 * callback.
 *
 * The `Incident` model has 5 columns:
 *   - `id` (autogenerated by Prisma)
 *   - `deviceId` (FK to Device)
 *   - `severity` (free-form String, mirrors Alert.severity)
 *   - `metric` (free-form String, mirrors Alert.metric)
 *   - `value` (Float, the alert's triggering reading)
 *   - `openedAt` (DateTime, defaults to now() at the schema layer
 *     — we pass the Alert's openedAt explicitly so the Incident's
 *     timeline aligns with the Alert's, not the write's clock
 *     skew).
 *
 * The `value` is the rule's `metricValue` (the reading that
 * breached the threshold), NOT a derived or aggregate — see spec
 * §"Incident.value semantics".
 */
export const buildIncidentPayload = (
  input: IncidentFromAlertInput,
): {
  readonly deviceId: string;
  readonly severity: string;
  readonly metric: RuleMetric;
  readonly value: number;
  readonly openedAt: Date;
} => ({
  deviceId: input.deviceId,
  severity: input.severity,
  metric: input.metric,
  value: input.value,
  openedAt: input.openedAt,
});
